version: '3.9'

services:
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "16333:6379"
  #   networks:
  #     - four-legged
  # redis-queue:
  #   image: "redis:alpine"
  #   ports:
  #     - "16334:6380"
  #   networks:
  #     - four-legged
  # mailer:
  #   image: schickling/mailcatcher
  #   ports: [1025, 1080]
  #   networks:
  #     - four-legged
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pets}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    networks:
      - four-legged
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "6528:5432"
  web:
    env_file: .env.local
    build:
      target: base
    networks:
      - four-legged
    
  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "9000:9000"
      - "5173:5173"
    command: npm run dev
    networks:
      - four-legged

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###

networks:
  four-legged:
    name: pet-pals
    driver: bridge